-keep class com.herohan.** { *; }
-keep class com.serenegiant.** { *; }
-keepclassmembers class * implements com.serenegiant.usb.IButtonCallback { *; }
-keepclassmembers class * implements com.serenegiant.usb.IFrameCallback { *; }
-keepclassmembers class * implements com.serenegiant.usb.IStatusCallback { *; }
